# These are supported funding model platforms

github: c0d3h01
patreon: #
open_collective: #
ko_fi: #
tidelift: #
community_bridge: #
liberapay: #
issuehunt: #
lfx_crowdfunding: #
polar: #
buy_me_a_coffee: c0d3h01
thanks_dev: #
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
