name: Android Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: Release
      ANDROID_PLATFORM: android-21
      ANDROID_NDK: ${{ github.workspace }}/android-ndk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (required for some Android tools)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          NDK_VERSION=r26c
          wget https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip
          unzip android-ndk-${NDK_VERSION}-linux.zip -d ${{ github.workspace }}
          mv ${{ github.workspace }}/android-ndk-${NDK_VERSION} $ANDROID_NDK

      - name: Install CMake & Ninja
        run: |
          sudo apt-get install -y cmake ninja-build

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Run full build
        run: ./build.sh all
